apiVersion: v1
kind: Service
metadata:
  name: ms-order-service
  namespace: polar
  labels:
    app: ms-order-service
spec:
  type: ClusterIP
  selector:
    app: ms-order-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9002
